condLabel = ["C1", "C2", "C3"];
triaLabel = ["A", "B", "C", "D"];
loopTrial = 'true';
numTrialRep = 2;
lab3 = ["ST", "EN"];
srtcor = 'true';
lab4 = "IDX";

vnames2 = {'a_min_gzx_c1', 'a_nsacc_c1', 'a_max_ampx_c1',...
    'a_max_amp_xy_c1', 'a_pvel_c1' 'a_xfix_c1', 'a_yfix_c1', 'a_maxfix_c1',...
    'a_acrcy_c1', 'a_latncy_c1', 'b_min_gzx_c1', 'b_nsacc_c1', 'b_max_ampx_c1',...
    'b_max_amp_xy_c1', 'b_pvel_c1' 'b_xfix_c1', 'b_yfix_c1', 'b_maxfix_c1',...
    'b_acrcy_c1', 'b_latncy_c1','c_max_gzx_c1', 'c_nsacc_c1', 'c_max_ampx_c1',...
    'c_max_amp_xy_c1', 'c_pvel_c1' 'c_xfix_c1', 'c_yfix_c1', 'c_maxfix_c1',...
    'c_acrcy_c1', 'c_latncy_c1','d_max_gzx_c1', 'd_nsacc_c1', 'd_max_ampx_c1',...
    'd_max_amp_xy_c1', 'd_pvel_c1' 'd_xfix_c1', 'd_yfix_c1', 'd_maxfix_c1',...
    'd_acrcy_c1', 'd_latncy_c1','a_min_gzx_c2', 'a_nsacc_c2', 'a_max_ampx_c2',...
    'a_max_amp_xy_c2', 'a_pvel_c2' 'a_xfix_c2', 'a_yfix_c2', 'a_maxfix_c2',...
    'a_acrcy_c2', 'a_latncy_c2', 'b_min_gzx_c2', 'b_nsacc_c2', 'b_max_ampx_c2',...
    'b_max_amp_xy_c2', 'b_pvel_c2' 'b_xfix_c2', 'b_yfix_c2', 'b_maxfix_c2',...
    'b_acrcy_c2', 'b_latncy_c2','c_max_gzx_c2', 'c_nsacc_c2', 'c_max_ampx_c2',...
    'c_max_amp_xy_c2', 'c_pvel_c2' 'c_xfix_c2', 'c_yfix_c2', 'c_maxfix_c2',...
    'c_acrcy_c2', 'c_latncy_c2','d_max_gzx_c2', 'd_nsacc_c2', 'd_max_ampx_c2',...
    'd_max_amp_xy_c2', 'd_pvel_c2' 'd_xfix_c2', 'd_yfix_c2', 'd_maxfix_c2',...
    'd_acrcy_c2', 'd_latncy_c2','a_min_gzx_c3', 'a_nsacc_c3', 'a_max_ampx_c3',...
    'a_max_amp_xy_c3', 'a_pvel_c3' 'a_xfix_c3', 'a_yfix_c3', 'a_maxfix_c3',...
    'a_acrcy_c3', 'a_latncy_c3', 'b_min_gzx_c3', 'b_nsacc_c3', 'b_max_ampx_c3',...
    'b_max_amp_xy_c3', 'b_pvel_c3' 'b_xfix_c3', 'b_yfix_c3', 'b_maxfix_c3',...
    'b_acrcy_c3', 'b_latncy_c3','c_max_gzx_c3', 'c_nsacc_c3', 'c_max_ampx_c3',...
    'c_max_amp_xy_c3', 'c_pvel_c3' 'c_xfix_c3', 'c_yfix_c3', 'c_maxfix_c3',...
    'c_acrcy_c3', 'c_latncy_c3','d_max_gzx_c3', 'd_nsacc_c3', 'd_max_ampx_c3',...
    'd_max_amp_xy_c3', 'd_pvel_c3' 'd_xfix_c3', 'd_yfix_c3', 'd_maxfix_c3',...
    'd_acrcy_c3', 'd_latncy_c3'};




